# Game settings and constants used across the frontend
WIDTH, HEIGHT = 920, 560
FPS = 120

# Colors
BG_COLOR = (245, 245, 245)
PLAYER_COLOR = (66, 206, 241)
ENEMY_COLOR = (255, 92, 92)
TEXT_COLOR = (34, 34, 34)
MENU_TITLE_COLOR = (240, 246, 255)
MENU_SUBTITLE_COLOR = (204, 217, 242)
BUTTON_TEXT_COLOR = (240, 246, 255)
BUTTON_BG_COLOR = (34, 50, 76)
BUTTON_BORDER_COLOR = (93, 157, 255)

# Player
PLAYER_SIZE = 35
PLAYER_SPEED = 300  # pixels per second

# Enemy
ENEMY_SIZE = 50
ENEMY_SPEED = 145  # pixels per second (slow)
SPAWN_DISTANCE = 320  # pixels away from player

# UI
FONT_NAME = None
SCORE_FONT_SIZE = 24
SCORE_POS = (16, 12)

# Pickups
PICKUP_SIZE = 28
PICKUP_IMAGE_SCALE = 1.4
PICKUP_YELLOW_COLOR = (255, 200, 0)
PICKUP_GREEN_COLOR = (70, 255, 120)
GREEN_PICKUP_CHANCE = 0.5

# Boosts
BOOST_SPEED_MULT = 1.25
BOOST_SIZE_ADD = 12
BOOST_DURATION_SECONDS = 20
BOOST_BAR_WIDTH = 140
BOOST_BAR_HEIGHT = 16
BOOST_BAR_OFFSET_Y = 40
BOOST_BAR_BG = (40, 40, 50)
BOOST_BAR_FILL = (255, 215, 0)
BOOST_LABEL_TEXT = "speed boost"
BOOST_LABEL_FONT_SIZE = 18
BOOST_LABEL_OFFSET_Y = 22
SPRITE_OVERSIZE = 1.2

# Enemy health bar
ENEMY_HEALTH_BAR_WIDTH = 420
ENEMY_HEALTH_BAR_HEIGHT = 18
ENEMY_HEALTH_BAR_RIGHT_WIDTH = 30
ENEMY_HEALTH_BAR_OFFSET_Y = 8
ENEMY_HEALTH_MAX = 100

# Menu and highscore settings
MENU_BUTTON_WIDTH = 240
MENU_BUTTON_HEIGHT = 52
MENU_BUTTON_SPACING = 18
MENU_BUTTON_COLOR = BUTTON_BG_COLOR
MENU_BUTTON_BORDER = BUTTON_BORDER_COLOR
MENU_BUTTON_TEXT_COLOR = BUTTON_TEXT_COLOR
MENU_OVERLAY_COLOR = (6, 12, 26, 180)
MENU_TITLE_FONT_SIZE = 58
MENU_SUBTITLE_FONT_SIZE = 24
HIGHSCORE_FILE = "highscores.txt"
HIGHSCORES_COUNT = 5

# Trap warning animation
TRAP_WARNING_PHASE_LEFT_DISTANCE = 15
TRAP_WARNING_PHASE_RIGHT_DISTANCE = 25
TRAP_WARNING_JUMP_HEIGHT = 30

# Pickup spawn timing
PICKUP_SPAWN_SCORE_FIRST = 100
PICKUP_SPAWN_INTERVAL_PRE150 = (200, 300)
PICKUP_SPAWN_INTERVAL_POST150 = (200, 300)

# Attack tuning and cooldowns
ATTACK1_SCORE_THRESHOLD = 150
ATTACK1_COOLDOWN = 350
ATTACK1_CHARGE_TIME = 0.4
ATTACK1_LOCK_ON_DELAY = 0.1
ATTACK1_SHOCKWAVE_SPEED = 260
ATTACK1_SPREAD_ANGLE = 24
ATTACK1_PARTICLE_COUNT = 21
ATTACK1_TARGET_DISTANCE = 58

ATTACK2_SCORE_THRESHOLD = 400
ATTACK2_COOLDOWN = 450
ATTACK2_LOCK_TIME = 0.3
ATTACK2_RUN_SPEED = 1300
ATTACK2_TRIGGER_DISTANCE = 270
ATTACK2_SEGMENT_WIDTH = 40
ATTACK2_BACKOFF_DISTANCE = 10
ATTACK2_DAMAGE = 5
ATTACK2_MISS_STUN = 5.0

ATTACK1_DAMAGE = 1
ATTACK1_PARTICLE_SIZE = 18
ATTACK4_DAMAGE = 1
ATTACK_REFLECT_DAMAGE_RATIO = 0.3
ENEMY_ENRAGE_SCORE_DURATION = 300
BLOCK_UNLOCK_SCORE = 50
SHIELD_UNLOCK_SCORE = 50
SHIELD_DURATION = 3.5
SHIELD_COOLDOWN = 16.0
SHIELD_CLOSE_RANGE = 120
SHIELD_RECT_LENGTH = 30
SHIELD_RECT_WIDTH = 80
SHIELD_COLOR = (80, 170, 255, 140)
SHIELD_BORDER_COLOR = (220, 240, 255)
SHIELD_REFLECT_DAMAGE = 50
PLAYER_HEALTH_MAX = 10
BOSS_DEATH_HEIGHT = 64
BOSS_DEATH_SPEED = 40
PLAYER_DEATH_HEIGHT = 64
PLAYER_DEATH_SPEED = 40

ATTACK3_COOLDOWN = 5
ATTACK3_GRAB_DURATION = 0.9
ATTACK3_DRAG_DURATION = 0.6
ATTACK3_THROW_DURATION = 0.2
ATTACK3_KNOCKBACK_STUN = 0.5
ATTACK3_HOLD_RAISE = 30
ATTACK3_SCENE_DELAY = 0.4

ATTACK4_SCORE_THRESHOLD = 800
ATTACK4_COOLDOWN = 800
ATTACK4_DURATION = 16.0
ATTACK4_SPAWN_INTERVAL = 0.4
ATTACK4_ZONE_SIZE = (180, 100)
ATTACK4_DRONE_SPEED = 220
ATTACK4_FADE_TIME = 0.7
ATTACK4_MARK_DURATION = 10.0
ATTACK_DAMAGE_HALF = 5

# Trap durations in seconds
TRAP_DURATION_ENEMY = 10
TRAP_DURATION_PLAYER = 5

# Visuals
RHOMBUS_SIZE = 18
IMAGE_FOLDER = "assests\\images"
BACKGROUND_IMAGE = "background.png"
PLAYER_IMAGE = "player.png"
PLAYER_SHADOW_IMAGE = "player_shadow.png"
ENEMY_IMAGE = "enemy.png"
BOOST_IMAGE = "boost.png"
TRAP_IMAGE = "trap.png"
PICKUP_GLOW_IMAGE = "pickup_glow.png"

#extra essensials
Py_running = 0